# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerngeistGateway < Formula
  desc "Self-hosted backend service for ACP-compatible agents"
  homepage "https://github.com/arafatamim/ferngeist-acp-gateway"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.12.0/ferngeist-gateway_0.12.0_darwin_amd64_brew.tar.gz"
      sha256 "3c9ac7a93f159de670f7bf28d888031eb1716617e2a8fa28c830313072654e08"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.12.0/ferngeist-gateway_0.12.0_darwin_arm64_brew.tar.gz"
      sha256 "a9eaab86c65bd9f9443ae7473cff9fe55e2a71d9aa434cab319d87574d9481f2"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.12.0/ferngeist-gateway_0.12.0_linux_amd64_brew.tar.gz"
      sha256 "3e0ee09fe7b39a79241db9bd4cf0b036d06028a921fc6221652f2ebbc38a76c8"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.12.0/ferngeist-gateway_0.12.0_linux_arm64_brew.tar.gz"
      sha256 "735826cc34e29c56405e2c83aa4aba308661ba66c6758940deb002a43b495174"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  def post_install
    # --keep-settings: upgrades reapply the existing install's options
    # (--remote/--port/...); --lan only sets first-install defaults.
    system "ferngeist-gateway", "daemon", "install", "--keep-settings", "--lan"
  end
end
