# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerngeistGateway < Formula
  desc "Self-hosted backend service for ACP-compatible agents"
  homepage "https://github.com/arafatamim/ferngeist-acp-gateway"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.10.0/ferngeist-gateway_0.10.0_darwin_amd64_brew.tar.gz"
      sha256 "380fce9ec537ece73073f80a33fc829af017897e4011bd0fc3b31270517d89ab"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.10.0/ferngeist-gateway_0.10.0_darwin_arm64_brew.tar.gz"
      sha256 "92d056ab99212d10e81e84d623150ead3b9226308a1604998ce6fe07aa373483"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.10.0/ferngeist-gateway_0.10.0_linux_amd64_brew.tar.gz"
      sha256 "b6290547f46264750debcd6f141dbaea6df8492d4cc73994968ebeed47fc0a77"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.10.0/ferngeist-gateway_0.10.0_linux_arm64_brew.tar.gz"
      sha256 "d9a2835d40db08fe3d4448d5683e5fbdd4d6424b21e63bb5e04c76b56c2793d4"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  def post_install
    system "ferngeist-gateway", "daemon", "install", "--lan"
    # Silence the periodic update-available notification: brew-managed
    # installs update via `brew upgrade`, never self-update. Mirror
    # packaging/postinstall.sh's env append (runs as the invoking user,
    # so the env file is user-writable). Wrapped so a path/parse hiccup
    # never fails the formula install (post_install failures abort).
    begin
      linux_env = File.expand_path("~/.local/share/ferngeist-gateway/config/daemon.env")
      mac_env = File.expand_path("~/Library/Application Support/Ferngeist Gateway/config/daemon.plist.env")
      env = File.file?(linux_env) ? linux_env : mac_env
      if File.file?(env)
        content = File.read(env)
        unless content.include?("FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=")
          File.open(env, "a") { |f| f.puts "FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=0" }
        end
      end
    rescue StandardError
      nil
    end
  end
end
