# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerngeistGateway < Formula
  desc "Self-hosted backend service for ACP-compatible agents"
  homepage "https://github.com/arafatamim/ferngeist-acp-gateway"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.9.1/ferngeist-gateway_0.9.1_darwin_amd64_brew.tar.gz"
      sha256 "c2c963e01e2460072d52cb1acd51f33c5fe532268e868045bdcfd0856048cd02"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.9.1/ferngeist-gateway_0.9.1_darwin_arm64_brew.tar.gz"
      sha256 "230cd4a8620388798b6fd6c753ac8f989865a292ba7f44c1e3478b68103d07df"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.9.1/ferngeist-gateway_0.9.1_linux_amd64_brew.tar.gz"
      sha256 "a6597f3794ea5fd2f42c90edf49ccff701eff4f400d7fa4bfac3aa49cb30ae6e"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.9.1/ferngeist-gateway_0.9.1_linux_arm64_brew.tar.gz"
      sha256 "eb9a846092120a84e48e4bffdf2e52096d6cbfd9efca3f7298d11e7b2d436425"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  def post_install
    system "ferngeist-gateway", "daemon", "install", "--lan"
    # Silence the periodic update-available notification: brew-managed
    # installs update via `brew upgrade`, never self-update. Mirror
    # packaging/postinstall.sh's env append (runs as the invoking user,
    # so the env file is user-writable). Wrapped so a path/parse hiccup
    # never fails the formula install (post_install failures abort).
    begin
      linux_env = File.expand_path("~/.local/share/ferngeist-gateway/config/daemon.env")
      mac_env = File.expand_path("~/Library/Application Support/Ferngeist Gateway/config/daemon.plist.env")
      env = File.file?(linux_env) ? linux_env : mac_env
      if File.file?(env)
        content = File.read(env)
        unless content.include?("FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=")
          File.open(env, "a") { |f| f.puts "FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=0" }
        end
      end
    rescue StandardError
      nil
    end
  end
end
