#!/bin/sh
# Runs after dpkg/rpm installs the binary. `daemon install` is idempotent and
# per-user; if HOME is unavailable (root package install), skip silently.
set -u

# The package installs the binary to /usr/bin; prefer it. Fall back to the
# self-managed path so an in-place upgrade of a manual install still registers
# the service.
if [ -x /usr/bin/ferngeist-gateway ]; then
    GATEWAY_BIN=/usr/bin/ferngeist-gateway
elif [ -n "${HOME:-}" ] && [ -x "$HOME/.local/share/ferngeist-gateway/bin/ferngeist-gateway" ]; then
    GATEWAY_BIN="$HOME/.local/share/ferngeist-gateway/bin/ferngeist-gateway"
else
    GATEWAY_BIN=
fi

if [ -n "$GATEWAY_BIN" ]; then
    "$GATEWAY_BIN" daemon install || true
fi

# Package-manager builds must not self-update. The daemon env file is
# regenerated by `daemon install`, so gate the update channel through the
# update-check env var instead: package builds are pinned by the package
# manager, so disable the periodic update-available check too. The env file is
# written before the service starts, so this takes effect on the next start.
if [ -n "${HOME:-}" ] && [ -f "$HOME/.local/share/ferngeist-gateway/config/daemon.env" ]; then
    if ! grep -q '^FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=' "$HOME/.local/share/ferngeist-gateway/config/daemon.env"; then
        printf '\nFERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=0\n' >> "$HOME/.local/share/ferngeist-gateway/config/daemon.env"
    fi
fi

exit 0
